#!/usr/bin/env perl

use FindBin qw/$Bin/;
use lib "$Bin/lib";
use Cwd qw/abs_path getcwd/;
use Test::Harness;

sub main {
  @ARGV = alltests() unless @ARGV;
  runtests(@ARGV);
}

main();

sub alltests {
  # if $Bin == 
  my $dir = "";
  if (abs_path($Bin) ne abs_path(getcwd())) {
    $dir = "$Bin/";
  }
  glob($dir."t/*.t");
}

